bases:
- ../base

resources:
- namespace.yaml

patchesJson6902:
- path: patches/host-volume-pv.yaml
  target:
    version: v1
    kind: PersistentVolume
    name: host-volume
- path: patches/host-volume-pvc.yaml
  target:
    version: v1
    kind: PersistentVolumeClaim
    name: host-volume-claim
- path: patches/ingress.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: app-ingress

namespace: production
