apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
  namespace: default
spec:
  selector:
    matchLabels:
      app: plex
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: plex
        tier: backend
        track: stable
    spec:
      containers:
      - name: plex
        image: linuxserver/plex:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        volumeMounts:
        - name: plex-persistent-storage
          mountPath: /config
          subPath: plex/config
        - name: plex-persistent-storage
          mountPath: /tv
          subPath: tv/
        - name: plex-persistent-storage
          mountPath: /movies
          subPath: movies/
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Syndey"
      volumes:
      - name: plex-persistent-storage
        persistentVolumeClaim:
          claimName: host-volume-claim
