---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
  namespace: default
spec:
  selector:
    matchLabels:
      app: sonarr
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: sonarr
        tier: backend
        track: stable
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        volumeMounts:
        - name: sonarr-persistent-storage
          mountPath: /config
          subPath: sonarr/config
        - name: sonarr-persistent-storage
          mountPath: /tv
          subPath: tv/
        - name: sonarr-persistent-storage
          mountPath: /downloads
          subPath: downloads/
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Syndey"
      volumes:
      - name: sonarr-persistent-storage
        persistentVolumeClaim:
          claimName: host-volume-claim
