---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
  namespace: default
spec:
  selector:
    matchLabels:
      app: jackett
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: jackett
        tier: backend
        track: stable
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        volumeMounts:
        - name: jackett-persistent-storage
          mountPath: /config
          subPath: jackett/config
        - name: jackett-persistent-storage
          mountPath: /downloads
          subPath: downloads/
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Syndey"
      volumes:
      - name: jackett-persistent-storage
        persistentVolumeClaim:
          claimName: host-volume-claim
