---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: jackett
  labels:
    app: jackett
spec:
  selector:
    app: jackett
    tier: backend
  ports:
  - protocol: TCP
    port: 9117
