---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
  namespace: default
spec:
  selector:
    matchLabels:
      app: radarr
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: radarr
        tier: backend
        track: stable
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        volumeMounts:
        - name: radarr-persistent-storage
          mountPath: /config
          subPath: radarr/config
        - name: radarr-persistent-storage
          mountPath: /movies
          subPath: movies/
        - name: radarr-persistent-storage
          mountPath: /downloads
          subPath: downloads/
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Syndey"
      volumes:
      - name: radarr-persistent-storage
        persistentVolumeClaim:
          claimName: host-volume-claim
